name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install https://github.com/smathot/seaborn/releases/download/adhoc%2F0.14.0datamatrix0/seaborn-0.14.0.dev0-py3-none-any.whl
          pip install https://github.com/smathot/statsmodels/releases/download/adhoc%2F0.1datamatrix0/statsmodels-0.0.0-cp313-cp313-linux_x86_64.whl
          pip install https://github.com/smathot/pingouin/releases/download/adhoc%2F0.5.5datamatrix0/pingouin-0.5.5-py3-none-any.whl
          pip install pytest pytest-cov fastnumbers numpy scipy prettytable openpyxl pandas json_tricks psutil
      - name: Test with pytest
        run: |
          pytest --cov=datamatrix testcases/
